client/src/pages/SignUp/component/Emailconfirm.js

Emailconfirm.js 파일을 EmailConfirm.js로 변경하고 파일 맨 위에 /* eslint-disable */을 넣어서 경고 문구를 나오지 않게 함

[UPDATE] change the file name add 'eslint-disable'

---

client/src/pages/SignUp/component/UserInfo.js

input 속성 중, onChange와 관련된 요소를 제거함

[UPDATE] remove onChange function

---

server/iam/pom.xml
server/iam/src/main/java/com/lhsk/iam/IamApplication.java
server/iam/src/main/java/com/lhsk/iam/domain/user/controller/UserController.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/mapper/UserMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/vo/UserVO.java
server/iam/src/main/java/com/lhsk/iam/domain/user/service/UserService.java
server/iam/src/main/resources/mybatis/mapper/test.xml
server/iam/src/main/resources/templates/index.html
server/iam/src/main/resources/templates/signup.html

[FIXED]
1. Package : dao -> mapper로 변경 
[ADD]
1. Package : service 생성
2. file : UserService.java, UserVo.java, UserMapper.java 생성
3. test.xml은 DB연결 테스트 용으로 생성함 
[UPDATE]
1. UserController.java
2. pom.xml : mustache dependency 위에 주석 추가()
3. UserVO.java 필드명 : snake_case -> camelCase로 수정

[FIXED] 디렉토리 및 mybatis 관련 수정 사항

---

node-server/config/config.js
node-server/index.js
node-server/models/Users.js
node-server/models/index.js
node-server/package-lock.json
node-server/package.json
node-server/routes/Users.js

[UPDATE] add config files and library 

---

client/src/App.css
client/src/App.js
client/src/commons/Common.css
client/src/commons/Navbar.js

css 공통 부분 만듦
common.css -> container, nav, cover, contents, footer 
app.css -> reset 및 root 설정
app.js에서 inner 클래스 삭제

[UPDATE] update css and add common with our role and delete container inner class

---

client/package.json
client/src/App.js
client/src/pages/Inquiry/Index.js

[ADD] add inquiry page files

---

client/src/App.css
client/src/commons/Navbar.js
client/src/pages/SignUp/Index.js
client/src/pages/SignUp/Steps.js
client/src/pages/SignUp/index.css

[UPDATE] update signup steps and css

---

node-server/index.js
node-server/models/Users.js
node-server/routes/Inquiry.js

[ADD] add api parts for Inquiry page

---

client/src/pages/LogIn/Index.js

login 폼 yum 추가(보안 필요)
(추후 css 및 컴포넌트 변경 예정)

[UPDATE] update login form

---

node-server/index.js
node-server/package-lock.json
node-server/package.json
node-server/routes/Inquiry.js
node-server/routes/Users.js

[UPDATE] modify api parts

---

client/src/pages/SignUp/Index.js
client/src/pages/SignUp/component/EmailConfirm.js
client/src/pages/SignUp/component/PersonalInfo.js
client/src/pages/SignUp/component/Result.js
client/src/pages/SignUp/component/UserInfo.js
client/src/pages/SignUp/index.css

[UPDATE] modify signup pages structure and design for api

---

node-server/routes/Users.js

user 생성에 객체가 생겼는지 판단하는 조건을 추가함

[UPDATE] add condition for user instance

---

client/src/pages/Inquiry/Index.js
client/src/pages/Inquiry/index.css

api 기능 수정하고 디테일 페이지로 이동을 위해 디자인 변경

[UPDATE] modify api function and design

---

node-server/index.js
node-server/routes/News.js

[UPDATE] add news api

---

client/src/pages/Inquiry/Index.js

[UPDATE] modify api function cause it occured data overlapping

---

server/iam/src/main/java/com/lhsk/iam/domain/user/controller/UserController.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/mapper/UserMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/vo/DetailUserVO.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/vo/UpdateUserVO.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/vo/UserVO.java
server/iam/src/main/java/com/lhsk/iam/domain/user/service/UserService.java
server/iam/src/main/java/com/lhsk/iam/global/config/auth/PrincipalDetails.java
server/iam/src/main/resources/mybatis/mapper/userMapper.xml

1. UserVO.java
1-1. @tostring 삭제
1-2. setter 수정 : @Setter 삭제, userNo를 제외하고 setter로 접근 가능하도록 수정
1-3. getUserCode -> getUserCodeList로변경
2. WithoutUserCodeUserVO.java -> DetailUserVO.java 로 클래스명 변경 / 주석 추가
3. UpdateUserVO.java
3-1. 주석 추가
3-2. setter 수정 : @Setter 삭제, userNo를 제외하고 setter로 접근 가능하도록 수정
4. userMapper.xml
4-1. updateUser : if 조건 추가
4-2. findAllUser : returnType을 DetailUserVO로 변경
5. api 주소 변경
user -> users
6. UserService.java
상태 값을 controller로 넘겨주는 코드 추가
7. 최초가입자의 userCode를 admin으로 적용하는 기능 구현

[UPDATE,FIX] Implement first signup user get admin, update API URL

---

client/package-lock.json
client/package.json
client/src/pages/Index/Index.js
client/src/pages/Index/index.css

- swiper 추가
- 인트로, 강점 제외하고 대부분 완성

[UPDATE] almost done index page with swiper

---

server/iam/src/main/java/com/lhsk/iam/domain/account/api/AccountClient.java
server/iam/src/main/java/com/lhsk/iam/domain/account/api/DataProcessor.java
server/iam/src/main/java/com/lhsk/iam/domain/account/model/vo/AccountApiVO.java

1. dataProcessor : 조회데이터를 가공하는 기능을 모아둔 클래스
2. VO의 자료형을 sql.Date에서 time.LocalDate로 변경

[ADD, UPDATE] : create DataProcessor.java and change field type of VO

---

client/src/pages/Index/Index.js
client/src/pages/Index/component/NewsSlider.js
client/src/pages/Index/index.css

- 슬라이드 컴포넌트 화
- 리로딩 시 깨지는 슬라이드 해결(but html로 들어가는 게 아닌, text로 들어가게 되므로 하나하나 replace 해줘야하는 단점)

[UPDATE] devide slide component and solve problems

---

client/src/pages/Inquiry/Index.js
client/src/pages/Inquiry/index.css
node-server/index.js

[UPDATE] inquiry account_no design

---

server/iam/src/main/java/com/lhsk/iam/domain/account/controller/AccountController.java
server/iam/src/main/java/com/lhsk/iam/domain/account/model/vo/AccountVO.java
server/iam/src/main/java/com/lhsk/iam/domain/account/service/AccountService.java
server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

[UPDATE] implement select account

---

server/iam/src/main/java/com/lhsk/iam/domain/admin/model/mapper/AdminMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/mapper/UserMapper.java
server/iam/src/main/resources/mybatis/mapper/adminMapper.xml
server/iam/src/main/resources/mybatis/mapper/userMapper.xml

user에 있는 부서 CRUD 쿼리,  인터페이스를 admin으로 이동

[UPDATE,FIX] admin 관련 쿼리 및 인터페이스를 user -> admin으로 이동

---

server/iam/src/main/java/com/lhsk/iam/domain/account/controller/AccountController.java
server/iam/src/main/java/com/lhsk/iam/domain/account/service/AccountService.java
server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

입출금 내역 조회시 response 값 중 계좌번호, 은행코드 추가로 보내는 코드로 수정

[FIX] 입출금내역 response 계좌번호, 은행코드 추가

---

server/iam/src/main/java/com/lhsk/iam/IamApplication.java
server/iam/src/main/java/com/lhsk/iam/domain/account/controller/AccountController.java
server/iam/src/main/java/com/lhsk/iam/domain/account/service/DataInitializer.java
server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/mapper/ReportMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/InoutAcctReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/LoanAcctReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/service/ReportService.java
server/iam/src/main/resources/mybatis/mapper/reportMapper.xml

1. 일일시재보고서 완성 (일반사용자와 매니저 이상급으로 분기별 처리함)
2. 일부 URI 엔드포인터가 /로 끝나던 코드 수정

[ADD, FIX] : 일일시재보고서 완성 및 일부 URI 수정

---

server/iam/src/main/java/com/lhsk/iam/domain/account/model/vo/UserAccountVO.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/controller/AdminController.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/model/mapper/AdminMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/service/AdminService.java

관리자 페이지에서 user에 계좌 조회 권한을 부여하는 API 작업 중

[UPDATE] Working admin's API about userAccount

---

server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

입출금 내역 조회시 오늘 날짜를 넣었을 때 발생하는 오류 수정

[FIX] fixed inoutToday APIs

---

client/src/App.js
client/src/hooks/useAxiosInterceptor.js
client/src/hooks/useRefreshToken.js
client/src/pages/DailyReport/Index.js
client/src/pages/DailyReport/component/ExcelExportComponent.js
client/src/pages/InOut/Index.js
client/src/pages/InOut/component/ExcelExportComponent.js
client/src/pages/InOut/inout.css
client/src/pages/Inquiry/Index.js

- interceptor와 refresh hook의 console.log 제거
- app.js에서 browserRouter 제거
- 일일시재보고서 페이지 작업 진행
- inout 페이지 엑셀 추가 및 input date value 날짜 조절
- inout 및 inquiry 페이지의 axios에서 ROLE_MANAGER를 추가

[UPDATE] Modify inquiry&inout pages and proceed with the daily report page

---

server/iam/src/main/java/com/lhsk/iam/domain/admin/controller/AdminController.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/service/AdminService.java
server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

[UPDATE] Working userAvailable API in admin page

---

server/iam/src/main/java/com/lhsk/iam/domain/account/model/mapper/AccountMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/mapper/ReportMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/DailyInoutAcctReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/DailyReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/InoutReportData.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/InoutReportRequestVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/InoutReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/service/ReportService.java
server/iam/src/main/resources/mybatis/mapper/accountMapper.xml
server/iam/src/main/resources/mybatis/mapper/reportMapper.xml

1. 일일시재보고서 데이터 API 완성했으나, 일부 수정할 사항이 남아있음.
2. 입출내역보고서 데이터 API 작성중

[ADD] : 일일시재보고서 일부 완성 및 입출내역보고서 작성중

---

client/src/pages/DailyReport/Index.js
client/src/pages/DailyReport/component/ExcelExportComponent.js
client/src/pages/InOut/Index.js
client/src/pages/Inquiry/Index.js

[UPDATE] Modify files related to excel component

---

server/iam/src/main/java/com/lhsk/iam/domain/account/model/vo/GrantAccountVO.java
server/iam/src/main/java/com/lhsk/iam/domain/account/model/vo/UserAccountVO.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/controller/AdminController.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/model/mapper/AdminMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/service/AdminService.java
server/iam/src/main/resources/mybatis/mapper/adminMapper.xml

관리자가 회원에서 계좌 열람 권한을 부여하는 API 완성

[UPDATE, ADD] Implement grantAccount in admin APIs

---

server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/InoutReportRequestVO.java
server/iam/src/main/java/com/lhsk/iam/global/config/CorsConfig.java
server/iam/src/main/java/com/lhsk/iam/global/config/jwt/TokenController.java

1. /reAccessToken -> /api/reAccessToken
2. 로그로 검증과정 확인가능

[UPDATE] : 토큰 검증과정 로그로 확인 및 토큰URI 수정

---

server/iam/src/main/java/com/lhsk/iam/domain/admin/controller/AdminController.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/model/mapper/AdminMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/model/vo/DeptVO.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/service/AdminService.java
server/iam/src/main/resources/mybatis/mapper/adminMapper.xml

[UPDATE, ADD] Implement dept APIs in admin

---

server/iam/src/main/resources/mybatis/mapper/adminMapper.xml

[FIX] Fixed select dept SQL

---

server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/DailyInoutAcctReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/DailyReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/LoanAcctReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/model/vo/TimeAcctReportVO.java
server/iam/src/main/java/com/lhsk/iam/domain/report/service/ReportService.java
server/iam/src/main/java/com/lhsk/iam/domain/user/controller/UserController.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/mapper/LoginMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/user/model/vo/LoginRequestVO.java
server/iam/src/main/java/com/lhsk/iam/domain/user/service/LoginService.java
server/iam/src/main/java/com/lhsk/iam/global/config/auth/PrincipalDetailsService.java
server/iam/src/main/java/com/lhsk/iam/global/config/jwt/JwtAuthenticationFilter.java
server/iam/src/main/java/com/lhsk/iam/global/config/jwt/JwtAuthorizationFilter.java
server/iam/src/main/java/com/lhsk/iam/global/config/jwt/TokenController.java
server/iam/src/main/java/com/lhsk/iam/global/email/controller/EmailController.java
server/iam/src/main/java/com/lhsk/iam/global/schedule/Scheduler.java

1. 컨트롤러에 작성된 로그아웃을 로그인 서비스로 이동
2. 사용하지 않는 import 정리

[UPDATE] : 로그아웃 기능을 서비스로 이동 및 import 정리

---

server/iam/src/main/java/com/lhsk/iam/domain/admin/controller/AdminController.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/model/mapper/AdminMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/admin/service/AdminService.java
server/iam/src/main/java/com/lhsk/iam/domain/user/controller/UserController.java
server/iam/src/main/resources/mybatis/mapper/adminMapper.xml

1. admin 권한 위임 구현 완료(위임 완료 후 로그아웃 됨)
2. 회원 탈퇴 시,  로그아웃 되는 코드 추가

[UPDATE, FIX] Implement grantAdmin API and UPDATE delete user after logout

---

server/iam/src/main/java/com/lhsk/iam/domain/account/controller/AccountController.java
server/iam/src/main/java/com/lhsk/iam/domain/account/model/mapper/AccountMapper.java
server/iam/src/main/java/com/lhsk/iam/domain/account/service/AccountService.java
server/iam/src/main/java/com/lhsk/iam/global/email/service/EmailService.java
server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

1. 입출내역 엑셀로 내보내기 완성
2. 인증 이메일 디자인 수정

[ADD] : 입출내역 엑셀로 내보내기 완성

---

server/iam/src/main/java/com/lhsk/iam/domain/admin/controller/AdminController.java

[FIX] 부서 조회 API URL 수정

---

server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

입출금 관련 API에서 SQL구문 isLoan 처리 누락된 것 수정

[FIX] fixed inout API query(isLoan)

---

server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java
server/iam/src/main/java/com/lhsk/iam/global/email/service/EmailService.java

[UPDATE] : 보고서 URI수정 및 이메일 디자인 변경

---

server/iam/src/main/java/com/lhsk/iam/domain/account/model/vo/InoutRequestVO.java
server/iam/src/main/java/com/lhsk/iam/domain/account/service/AccountService.java
server/iam/src/main/resources/mybatis/mapper/accountMapper.xml

1. isLoan 타입 boolean -> int로 변경 (0: 수시입출&예/적금, 1:대출)
2. SQL WHEN 조건문 수정

[FIX] 입출금 API isLoan 타입 int로 수정, SQL 구문 수정

---

.github/workflows/deploy.yml

[FIX] : CI/CD 빌드 오류 수정

---

server/iam/src/main/java/com/lhsk/iam/global/email/service/EmailService.java

[FIX] : 이메일 인증 코드 수정

---

server/iam/src/main/java/com/lhsk/iam/domain/account/api/AccountClient.java

[UPDAET] : 프로퍼티 테스트중

---

server/iam/src/main/java/com/lhsk/iam/domain/account/api/AccountClient.java
server/iam/src/main/java/com/lhsk/iam/domain/account/service/DataInitializer.java

WebClient로 API데이터를 송수신하는데 문제가 발생하여 로그 확인중입니다

[UPDATE] : 깃허브 액션중 에러에 관한 로그 확인중

---

client/src/App.css
client/src/pages/Dashboard/Index.js
client/src/pages/Dashboard/dashboard.css
client/src/pages/LogIn/Index.js
client/src/pages/LogIn/login.css
client/src/pages/Mypage/component/UpdateInfo.js
client/src/pages/SignUp/Index.js
client/src/pages/SignUp/component/PersonalInfo.js
client/src/pages/SignUp/signup.css
server/iam/src/main/java/com/lhsk/iam/domain/dashboard/service/DashboardService.java

대시보드 자산합계시, total balance를 null일때 0으로 치환해서 보내는 코드 추가

[FIX] fixed total balance sum in dashboard AND frontEnd by yell

---

client/src/commons/SideNavReport.js
client/src/index.js
client/src/pages/Admin/Index.js
client/src/pages/Admin/admin.css
client/src/pages/Admin/component/Detail.js
client/src/pages/DailyReport/Index.js
client/src/pages/DailyReport/dailyreport.css
client/src/pages/Dashboard/Index.js
client/src/pages/InOut/Index.js
client/src/pages/InOut/inout.css
client/src/pages/InoutReport/Index.js
client/src/pages/InoutReport/inoutReport.css
client/src/pages/Inquiry/Index.js
client/src/pages/Inquiry/inquiry.css
client/src/pages/Mypage/component/UpdateInfo.js

It's Yell lol

---

client/src/App.css
client/src/commons/Common.css
client/src/commons/Navbar.js
client/src/pages/Index/index.css
client/src/pages/InoutReport/Index.js
client/src/pages/InoutReport/component/ExcelExportComponent.js

[UPDATE] modify design and logic

---

client/package.json
client/src/commons/Common.css
client/src/pages/DailyReport/Index.js
client/src/pages/DailyReport/component/EmailExportComponent.js
client/src/pages/InOut/Index.js

- common css 수정
- 이메일 내보내기 관련 추가

[UPDATE] modify design and ExcelExportComponent

---

server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java
server/iam/src/main/java/com/lhsk/iam/global/email/service/EmailService.java

[UPDATE] : 이메일 첨부파일명 및 제목 변경

---

server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java

[FIX] : 파일명 오류 수정

---

client/src/pages/DailyReport/Index.js
client/src/pages/DailyReport/component/EmailExportComponent.js
client/src/pages/DailyReport/component/ExcelExportComponent.js
client/src/pages/InoutReport/Index.js
client/src/pages/InoutReport/component/EmailExportComponent.js
client/src/pages/Inquiry/Index.js
client/src/pages/Inquiry/component/EmailExportComponent.js

[UPDATE] modify files related to excel, email component

---

server/iam/src/main/java/com/lhsk/iam/domain/report/controller/ReportController.java

[FIX] : 파일명 재변경

---

server/iam/src/main/java/com/lhsk/iam/global/config/CorsConfig.java
server/iam/src/main/java/com/lhsk/iam/global/email/service/EmailService.java

[UPDATE] : 네트리 파이로 전환

---

client/src/commons/Common.css
client/src/commons/Navbar.js

[UPDATE] change navbar design

---

client/src/pages/InOut/Index.js
client/src/pages/InoutReport/component/EmailExportComponent.js
client/src/pages/Inquiry/component/EmailExportComponent.js
client/src/pages/LogIn/login.css
client/src/pages/SignUp/signup.css

[UPDATE] change design for signup, login page

---

client/src/commons/Common.css

[UPDATE] change the design for navbar

---

client/src/commons/Common.css

[UPDATE] change the design

---

server/iam/src/main/java/com/lhsk/iam/domain/admin/service/AdminService.java
server/iam/src/main/java/com/lhsk/iam/global/config/CorsConfig.java

1. 위임하려는 매니저의 userNo와 userCode만 받도록 변경
2. Cosconfig를 locahost로 임시 변경

[FIX] 관리자 권한 위임 리퀘스트 파라미터 변경& Cosconfig 임시 변경

---

client/src/App.js
client/src/commons/Common.css
client/src/pages/InOut/Index.js

- app.js beforeunload 주석
- inout 페이지 select 오류 수정
- 디자인 수정

[FIX] modify error
